# Site settings
title: Molecular Dynamics and Oncology Progression Laboratory - Universidad de Concepción - Chile
lab_name: MDOP-Labs
author: >
  Alexis Salas and the Molecular Dynamics and Oncology Progression Laboratory
institution: UDEC 
email: alsalas@udec.cl
description: >
  The Molecular Dynamics and Oncology Progression Laboratory combines molecular biology, molecular dynamics, and bioinformatics methodologies to understand cancer genesis and progression.
baseurl: ""
url: "https://nanocell-lab.github.io"
twitter_username: alsalas7
github_username:  alsalas
images_dir: "/images/"

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/

#plugins for search engine optimization
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
