# Site settings
title: Laboratorio de Dinámica Molecular y Progresión Oncológica - Universidad de Concepción - Chile
lab_name: Laboratorio de Dinámica Molecular y Progresión Oncológica
author: >
  Alexis Salas y el Laboratorio de Dinámica Molecular y Progresión Oncológica
institution: UDEC 
email: alsalas@udec.cl
description: >
  El Laboratorio de Dinámica Molecular y Progresión Oncológica combina biología molecular, dinámica molecular y metodologías bioinformáticas para comprender la génesis y progresión del cáncer.
baseurl: ""
url: "https://nanocell-lab.github.io"
twitter_username: alsalas7
github_username:  alsalas
images_dir: "/images/"

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/

#plugins for search engine optimization
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
