# Site settings
title: Cancer`s Molecular Dynamics Laboratory at Universidad de Concepción - Chile
lab_name: CMDL Laboratory
author: >
  Alexis Salas and CMD laboratory
institution: UDEC 
email: alsalas@udec.cl
description: >
  The CMD Laboratory combines molecular biology, analysis of molecular dynamics, and bioinformatics methodologies for the design, analysis, and techniques for the validation of the biological hypotheses.
baseurl: ""
url: "https://nanocell-lab.github.io"
twitter_username: alsalas
github_username:  alsalas
images_dir: "/images/"

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/

#plugins for search engine optimization
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
